version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:80" # Map port 3000 to nginx port 80
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./server:/usr/src/app
    command: npm start

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
